name: [Develop] Node.js Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
      working-directory: ./src/client/recipes-app/
    - run: npm run build --if-present
      working-directory: ./src/client/recipes-app/
    - run: npm test
      working-directory: ./src/client/recipes-app/
